# almalinux is exactly same as Redhat image, but completely free
FROM almalinux:9
LABEL COURSE="Docker" \
      TRAINER="siva" \
      STUDENT="Vijju" \
      DURATION="10 days" \
      AUTHOR="Its me"