ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
      TRAINER="siva" \
      STUDENT="Vijju" \
      DURATION="10 days" \
      AUTHOR="Its me"
RUN echo "Student is: ${STUDENT}"
CMD ["sleep", "200"]